function ESS_LIBRARY = getESSLibrary()
%% Reference: Electricity storage and renewables: Costs and markets to 2030 IRENA				
% Selected Scenario: 2025 Reference
% CO2 : Comparative life cycle assessment of lithium-ion battery chemistries for residential storage
%https://doi.org/10.1016/j.est.2020.101230
%LTO: Life cycle assessment of the lithium titanate batteries used for electric vehicles.
%Supercap: Optimizing energy Dynamics: A comprehensive analysis of hybrid energy 
%storage systems integrating battery banks and supercapacitors
% SupercapCO2cost: Rethinking residential energy storage: GHG minimization potential of a Carbon Reinforced Concrete facade with function integrated supercapacitors
%%
    ESS_LIBRARY = struct(...
        'PumpedHydro', struct(...
            'name', 'Pumped Hydro Storage', ...
            'cycle_life', 50000, ... % equivalent full-cycles
            'calendar_life', 60, ... % a: years
            'depth_of_discharge', 90, ... % percenatge(%)
            'round_trip_efficiency', 80, ...% percenatge(%)
            'self_discharge_daily', 0.0, ...% percenatge per day
            'power_dynamic_response', 30.0, ...  % seconds to rated power
            'planning_construction_time', 15.0, ... % a: years
            'energy_installation_cost', 21.0, ...  % USD/kWh
            'power_installation_cost', 840.0, ...  % USD/kW
            'technology_type', 'mechanical' ...
        ), ...
        'CAES', struct(...
            'name', 'Compressed Air Energy Storage', ...
            'cycle_life', 50000, ...
            'calendar_life', 50, ...
            'depth_of_discharge', 40, ...
            'round_trip_efficiency', 67, ...
            'self_discharge_daily', 0.5, ...
            'power_dynamic_response', 480.0, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 45.7, ...
            'power_installation_cost', 712.7, ...
            'technology_type', 'mechanical' ...
        ), ...
        'Flywheel', struct(...
            'name', 'Flywheel', ...
            'cycle_life', 260954, ...
            'calendar_life', 26.1, ...
            'depth_of_discharge', 85, ...
            'round_trip_efficiency', 86, ...
            'self_discharge_daily', 45.6, ...
            'power_dynamic_response', 0.05, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 2280.7, ...
            'power_installation_cost', 228.1, ...
            'technology_type', 'mechanical' ...
        ), ...
        'FloodedLA', struct(...
            'name', 'Flooded Lead Acid', ...
            'cycle_life', 2453.6, ...
            'calendar_life', 11.3, ...
            'depth_of_discharge', 50, ...
            'round_trip_efficiency', 84.2, ...
            'self_discharge_daily', 0.3, ...
            'power_dynamic_response', 0.006, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 94.4, ...
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
                'VRLA', struct(...
            'name', 'VR Lead Acid', ...
            'cycle_life', 2453.6, ...
            'calendar_life', 11.3, ...
            'depth_of_discharge', 50, ...
            'round_trip_efficiency', 82.2, ...
            'self_discharge_daily', 0.3, ...
            'power_dynamic_response', 0.006, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 168.6, ...
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
        'LFP', struct(...
            'name', 'Lithium Iron Phosphate', ...
            'Embedded_CO2', 217, ...% kgCO2/kWh (Only production CO2)
            'cycle_life', 15157, ...
            'calendar_life', 26, ...
            'depth_of_discharge', 100, ...
            'SOC_min', 10, ...%Sizing of Hybrid Energy Storage Systems Using Recurring Daily Patterns by Shahab Karari
            'SOC_max', 90, ...
            'round_trip_efficiency', 95.1, ...
            'self_discharge_daily', 0.1, ...
            'power_dynamic_response', 0.01, ...
            'planning_construction_time', 0.0, ...
            'installation_cost', 108.6, ...% Energy Best cost for year 2025 USD/kWh
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
        'NCA', struct(...
            'name', 'Lithium Nickel Cobalt Acid', ...
            'Embedded_CO2', 225, ...% kgCO2/kWh (Only production CO2)
            'cycle_life', 1515.7, ...
            'calendar_life', 15.8, ...
            'depth_of_discharge', 90, ...
            'SOC_min', 10, ...%Sizing of Hybrid Energy Storage Systems Using Recurring Daily Patterns by Shahab Karari
            'SOC_max', 90, ...
            'round_trip_efficiency', 96.1, ...
            'self_discharge_daily', 0.2, ...
            'power_dynamic_response', 0.01, ...
            'planning_construction_time', 0.0, ...
            'installation_cost', 199.1, ... %energy cost of battery $/kWh
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
        'NMC', struct(...%https://www.sciencedirect.com/science/article/pii/S2772390923000392#f0015
            'name', 'Lithium Nickel Manganese Cobalt', ...
            'Embedded_CO2', 201, ...% kgCO2/kWh (Only production CO2)
            'cycle_life', 3031, ...
            'calendar_life', 15.8, ...
            'depth_of_discharge', 90, ...
            'SOC_min', 10, ...%Sizing of Hybrid Energy Storage Systems Using Recurring Daily Patterns by Shahab Karari
            'SOC_max', 90, ...
            'round_trip_efficiency', 96.1, ...
            'self_discharge_daily', 0.1, ...
            'power_dynamic_response', 0.01, ...
            'planning_construction_time', 0.0, ...
            'installation_cost', 232.4, ... %energy cost of battery $/kWh
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
        'LTO', struct(...
            'name', 'Lithium Titanate', ...
            'Embedded_CO2', 407, ...% kgCO2/kWh (Only production CO2)
            'cycle_life', 15157.3, ...
            'calendar_life', 19.7, ...
            'depth_of_discharge', 95, ...
            'SOC_min', 10, ...%Sizing of Hybrid Energy Storage Systems Using Recurring Daily Patterns by Shahab Karari
            'SOC_max', 90, ...
            'round_trip_efficiency', 97.1, ...
            'self_discharge_daily', 0.1, ...
            'power_dynamic_response', 0.01, ...
            'planning_construction_time', 0.0, ...
            'installation_cost', 633.1, ...%energy cost of battery $/kWh
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
        'NaNiCl', struct(...
            'name', 'Sodium Nickle Chrolide', ...
            'cycle_life', 3914.3, ...
            'calendar_life', 19.6, ...
            'depth_of_discharge', 100, ...
            'round_trip_efficiency', 86, ...
            'self_discharge_daily', 5, ...
            'power_dynamic_response', 0.5, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 222.9, ...%energy cost of battery $/kWh
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
        'NaS', struct(...
            'name', 'Sodium Sulfur', ...
            'cycle_life', 6488, ...
            'calendar_life', 21.4, ...
            'depth_of_discharge', 100, ...
            'round_trip_efficiency', 83.2, ...
            'self_discharge_daily', 0.1, ...
            'power_dynamic_response', 10.0, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 217.0, ...
            'power_installation_cost', 0.0, ...
            'technology_type', 'battery' ...
        ), ...
        'VanadiumFlow', struct(...
            'name', 'Vanadium Redox Flow', ...
            'cycle_life', 13000, ...
            'calendar_life', 16.2, ...
            'depth_of_discharge', 100, ...
            'round_trip_efficiency', 75.1, ...
            'self_discharge_daily', 0.2, ...
            'power_dynamic_response', 0.01, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 174.2, ...
            'power_installation_cost', 818.2, ...
            'technology_type', 'flow' ...
        ), ...
        'ZnBrFlow', struct(...
            'name', 'Zinc Bromine Flow', ...
            'cycle_life', 10000, ...
            'calendar_life', 13.5, ...
            'depth_of_discharge', 100, ...
            'round_trip_efficiency', 75.1, ...
            'self_discharge_daily', 15.0, ...
            'power_dynamic_response', 0.01, ...
            'planning_construction_time', 0.0, ...
            'energy_installation_cost', 452.3, ...
            'power_installation_cost', 0.0, ...
            'technology_type', 'flow' ...
        ), ...
        'SC', struct(...
            'name', 'Generic Supercapcaitor', ...
            'Embedded_CO2', 0.0057, ...% kgCO2/kWh (cradle to grave CO2) 5,65 kgCO2-eq/MWh
            'calendar_life', 10, ...
            'depth_of_discharge', 80, ...
            'SOC_min', 10, ...%
            'SOC_max', 90, ...
            'round_trip_efficiency', 90, ...
            'self_discharge', 0.001, ...
            'installation_cost', 748, ...%$/kW Capital cost
            'OMC', 0.02, ...%$/kWh
            'replacement_cost', 748 ...
        ) ...
    );
end