%%
%Modeling, integration, and optimal selection of the turbine technology in the
%hybrid wind-photovoltaic renewable energy system design Energy Conversion and Management 205 (2020) 112350
%CarbonCost:https://windeurope.org/wp-content/uploads/files/policy/position-papers/20240206-WindEurope-discussion-paper-LCAs-in-wind-energy-auctions.pdf
%%
function WT_LIBRARY = getWindTurbineLibrary()
    WT_LIBRARY = struct(...
        'wt1', struct(...
            'rated_power', 20, ...%kW
            'embedded_CO2', 14.2, ...%gCO2/kWh
            'cut_in_speed', 3, ...%m/s
            'cut_out_speed', 25, ...%m/s
            'rated_speed', 11.6, ...%m/s
            'life', 30, ...%Years
            'IC', 29979, ...%$
            'RC', 29979 , ...%$
            'OMC',0.02*29979  ...% 799$/Year
        ), ...
        'wt2', struct(...
            'rated_power', 30, ...
            'cut_in_speed', 6.1, ...
            'cut_out_speed', 3, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 44952, ...
            'RC', 44952 * 0.05, ...
            'OMC', 1198 ...
        ), ...
        'wt3', struct(...
            'rated_power', 35, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11, ...
            'life', 25, ...
            'IC', 52435, ...
            'RC', 52435 * 0.05, ...
            'OMC', 1398 ...
        ),...
        'wt4', struct(...
            'rated_power', 50, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 23, ...
            'rated_speed', 11.3, ...
            'life', 30, ...
            'IC', 74868, ...
            'RC', 74868 * 0.05, ...
            'OMC', 1996 ...
        ),...
        'wt5', struct(...
            'rated_power', 50, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 30, ...
            'rated_speed', 11, ...
            'life', 25, ...
            'IC', 74868, ...
            'RC', 74868 * 0.05, ...
            'OMC', 1996 ...
        ),...
        'wt6', struct(...
            'rated_power', 50, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11, ...
            'life', 25, ...
            'IC', 74868, ...
            'RC', 74868 * 0.05, ...
            'OMC', 1996 ...
        ),...
        'wt7', struct(...
            'rated_power', 65, ...
            'cut_in_speed', 3.6, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11, ...
            'life', 25, ...
            'IC', 97278, ...
            'RC', 97278 * 0.05, ...
            'OMC', 2594 ...
        ),...
        'wt8', struct(...
            'rated_power', 65, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 25, ...
            'rated_speed', 15, ...
            'life', 25, ...
            'IC', 97278, ...
            'RC', 97278 * 0.05, ...
            'OMC', 2594 ...
        ),...
        'wt9', struct(...
            'rated_power', 75, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 14, ...
            'life', 25, ...
            'IC', 112204, ...
            'RC', 112204 * 0.05, ...
            'OMC', 2992 ...
        ),...
        'wt10', struct(...
            'rated_power', 80, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 25, ...
            'rated_speed', 15, ...
            'life', 25, ...
            'IC', 119664, ...
            'RC', 119664 * 0.05, ...
            'OMC', 3191 ...
        ),...
        'wt11', struct(...
            'rated_power', 100, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 25, ...
            'rated_speed', 10, ...
            'life', 25, ...
            'IC', 149475, ...
            'RC', 149475 * 0.05, ...
            'OMC', 3986 ...
        ),...
        'wt12', struct(...
            'rated_power', 100, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 20, ...
            'rated_speed', 9, ...
            'life', 25, ...
            'IC', 149475, ...
            'RC', 149475 * 0.05, ...
            'OMC', 3986 ...
        ),...
        'wt13', struct(...
            'rated_power', 100, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11, ...
            'life', 25, ...
            'IC', 149475, ...
            'RC', 149475 * 0.05, ...
            'OMC', 3986 ...
        ),...
        'wt14', struct(...
            'rated_power', 108, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 27, ...
            'rated_speed', 15, ...
            'life', 25, ...
            'IC', 161387, ...
            'RC', 161387 * 0.05, ...
            'OMC', 4303 ...
        ),...
        'wt15', struct(...
            'rated_power', 130, ...
            'cut_in_speed', 20.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 13, ...
            'life', 25, ...
            'IC', 194112, ...
            'RC', 194112 * 0.05, ...
            'OMC', 5176 ...
        ),...
        'wt16', struct(...
            'rated_power', 150, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 223818, ...
            'RC', 223818 * 0.05, ...
            'OMC', 5968 ...
        ),...
        'wt17', struct(...
            'rated_power', 150, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 223818, ...
            'RC', 223818 * 0.05, ...
            'OMC', 5968 ...
        ),...
        'wt18', struct(...
            'rated_power', 150, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12.6, ...
            'life', 25, ...
            'IC', 223818, ...
            'RC', 223818 * 0.05, ...
            'OMC', 5968 ...
        ),...
        'wt19', struct(...
            'rated_power', 150, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 24, ...
            'rated_speed', 14, ...
            'life', 25, ...
            'IC', 223818, ...
            'RC', 223818 * 0.05, ...
            'OMC', 5968 ...
        ),...
        'wt20', struct(...
            'rated_power', 200, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 25, ...
            'rated_speed', 10.5, ...
            'life', 25, ...
            'IC', 297900, ...
            'RC', 297900 * 0.05, ...
            'OMC', 7944 ...
        ),...
        'wt21', struct(...
            'rated_power', 225, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 14.5, ...
            'life', 25, ...
            'IC', 334842, ...
            'RC', 334842 * 0.05, ...
            'OMC', 8929 ...
        ),...
        'wt22', struct(...
            'rated_power', 225, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 14, ...
            'life', 25, ...
            'IC', 334842, ...
            'RC', 334842 * 0.05, ...
            'OMC', 8929 ...
        ),...
        'wt23', struct(...
            'rated_power', 300, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 20, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 445275, ...
            'RC', 445275 * 0.05, ...
            'OMC', 11874 ...
        ),...
        'wt24', struct(...
            'rated_power', 335, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 496608, ...
            'RC', 496608 * 0.05, ...
            'OMC', 13242 ...
        ),...
        'wt25', struct(...
            'rated_power', 1000, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 22, ...
            'rated_speed', 12.5, ...
            'life', 25, ...
            'IC', 1447500, ...
            'RC', 1447500 * 0.05, ...
            'OMC', 38600 ...
        ),...
        'wt26', struct(...
            'rated_power', 1500, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11.1, ...
            'life', 25, ...
            'IC', 2131875, ...
            'RC', 2131875 * 0.05, ...
            'OMC', 56850 ...
        ),...
        'wt27', struct(...
            'rated_power', 1500, ...%kW
            'embedded_CO2', 14.2, ...%gCO2/kWh
            'cut_in_speed', 4, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11.6, ...
            'hub_height', 80, ... %(meters)https://en.wind-turbine-models.com/turbines/777-acciona-aw-70-1500 
            'life', 25, ...
            'IC', 1421, ...%2131875$ for 1.5MW each turbine--2131875$/1500kW=1421$/kW
            'RC', 1421* 0.8, ...
            'OMC', 1421*0.02 ...
        ),...
        'wt28', struct(...
            'rated_power', 1500, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11, ...
            'life', 25, ...
            'IC', 2131875, ...
            'RC', 2131875 * 0.05, ...
            'OMC', 56850 ...
        ),...
        'wt29', struct(...
            'rated_power', 1650, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 20, ...
            'rated_speed', 12, ...
            'life', 20, ...
            'IC', 2332068, ...
            'RC', 2332068 * 0.05, ...
            'OMC', 62188 ...
        ),...
        'wt30', struct(...
            'rated_power', 1650, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 20, ...
            'rated_speed', 12, ...
            'life', 20, ...
            'IC', 2332068, ...
            'RC', 2332068 * 0.05, ...
            'OMC', 62188 ...
        ),...
        'wt31', struct(...
            'rated_power', 2500, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 11, ...
            'life', 25, ...
            'IC', 3421875, ...
            'RC', 3421875 * 0.05, ...
            'OMC', 91250 ...
        ),...
        'wt32', struct(...
            'rated_power', 2500, ...
            'cut_in_speed', 3.5, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 3421875, ...
            'RC', 3421875 * 0.05, ...
            'OMC', 91250 ...
        ),...
        'wt33', struct(...
            'rated_power', 3000, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 4050000, ...
            'RC', 4050000 * 0.05, ...
            'OMC', 108000 ...
        ),...
        'wt34', struct(...
            'rated_power', 3000, ...
            'cut_in_speed', 4, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 4050000, ...
            'RC', 4050000 * 0.05, ...
            'OMC', 108000 ...
        ),...
        'wt35', struct(...
            'rated_power', 3000, ...
            'cut_in_speed', 3, ...
            'cut_out_speed', 25, ...
            'rated_speed', 12, ...
            'life', 25, ...
            'IC', 4050000, ...
            'RC', 4050000 * 0.05, ...
            'OMC', 108000 ...
        )...
    );
end
